<?php 
    $location = [
        'state' => [
                'ACT' => 'Australian Capital Territory',
                'NSW' =>'New South Wales',
                'NT' =>'Northern Territory',
                'QLD' =>'Queensland',
                'SA' =>'South Australia',
                'TAS' =>'Tasmania',
                'VIC' =>'Victoria',
                'WA' =>'Western Australia',
                ],
        'city' => [
            'NSW' => [
              '1' => 'Sydney',
              '2' => 'Albury',
              '3' => 'Armidale',
              '4' => 'Bathurst',
              '5' => 'Broken Hill',
              '6' => 'Cessnock',
              '7' => 'Coffs Harbour',
              '8' => 'Dubbo',
              '9' => 'Gosford',
              '10' => 'Goulburn',
              '11' => 'Grafton',
              '12' => 'Griffith',
              '13' => 'Lake Macquarie',
              '14' => 'Lismore',
              '15' => 'Maitland',
              '16' => 'Newcastle',
              '17' => 'Nowra',
              '18' => 'Orange',
              '19' => 'Port Macquarie',
              '20' => 'Queanbeyan',
              '21' => 'Tamworth',
              '22' => 'Tweed Heads',
              '23' => 'Wagga Wagga',
              '24' => 'Wollongong',
              '25' => 'Wyong',
            ],
            'NT' => [
              '26' => 'Darwin',
              '27' => 'Alice Springs',
              '28' => 'Katherine',
              '29' =>  'Darwin', 'Palmerston',
            ],
            'QLD' => [
              '30' =>   'Brisbane',
              '31' =>   'Bundaberg',
              '32' =>   'Cairns',
              '33' =>   'Charters Towers',
              '34' =>   'Gladstone',
              '35' =>   'Gold Coast',
              '36' =>   'Gympie',
              '37' =>   'Hervey Bay',
              '38' =>   'Ipswich',
              '39' =>  'Logan City',
              '40' =>  'Mackay',
              '41' =>  'Maryborough',
              '42' =>  'Mount Isa',
              '43' =>  'Nambour',
              '44' =>  'Redcliffe',
              '45' =>  'Rockhampton',
              '46' =>  'Sunshine Coast',
              '47' =>  'Thuringowa',
              '48' =>  'Toowoomba',
              '49' =>  'Townsville',
            ],
            'SA' => [
             '50' => 'Adelaide',
             '51' => 'Mount Gambier',
             '52' => 'Murray Bridge',
             '53' => 'Port Augusta',
             '54' => 'Port Pirie',
             '55' => 'Port Lincoln',
             '56' => 'Victor Harbor',
             '57' => 'Whyalla',
            ],
            'TAS' => [
              '58' =>  'Hobart',
              '59' =>  'Burnie',
              '60' =>  'Clarence',
              '61' =>  'Devonport',
              '62' =>  'Glenorchy',
              '63' =>  'Launceston',
            ],
            'VIC' => [
              '64' =>  'Melbourne',
              '65' =>  'Benalla',
              '66' =>  'Ballarat',
              '67' =>  'Bendigo',
              '68' =>  'Geelong',
              '69' =>  'Latrobe City',
              '70' =>  'Mildura',
              '71' =>  'Shepparton',
              '72' =>  'Swan Hill',
              '73' => 'Wangaratta',
              '74' => 'Warrnambool',
              '75' => 'Wodonga',
            ],
            'WA' => [
               '76' =>  'Perth',
               '77' =>  'Albany',
               '78' =>  'Broome',
               '79' =>  'Bunbury',
               '80' =>  'Geraldton',
               '81' =>  'Fremantle',
               '82' =>  'Kalgoorlie',
               '83' =>  'Mandurah',
               '84' =>  'Port Hedland',
            ],
            'ACT' => [
               '85' => 'Canberra',
            ],
        ],
    ];
?>